name_or_path: /data/models/huggingface/lmsys/vicuna-7b-v1.5
tokenizer_name_or_path: null
archive: null
block_name: LlamaDecoderLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16
